#ifndef ENUMS_H
#define ENUMS_H

enum TOOL {SELECT, PENCIL, CIRCLE, TRIANGLE, RECTANGLE, POLYGON};

enum ACTION {NONE, CLEAR, ERASE, SIZEUP, SIZEDOWN, BRINGFRONT, PUTBACK};

enum COLOR {RED, ORANGE, YELLOW, GREEN, BLUE, INDIGO, VIOLET};

#endif